import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Rohan',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'anmol',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'kate spade purse',
      slug: 'kate-spade-purse',
      category: 'Purse',
      images: '/images/p1.jpg',
      price: 130,
      countInStock: 5,
      brand: 'kate spade',
      rating: 4.5,
      numReviews: 10,
      description: 'abc',
    },
    {
      // _id: '2',
      name: 'kate spade black purse',
      slug: 'kate-spade-black-purse',
      category: 'Purse',
      images: '/images/p2.jpg',
      price: 130,
      countInStock: 5,
      brand: 'kate spade',
      rating: 4,
      numReviews: 10,
      description: 'bcd',
    },
    {
      // _id: '3',
      name: 'kate spade shoes',
      slug: 'kate-spade-shoes',
      category: 'shoes',
      images: '/images/p3.jpg',
      price: 90,
      countInStock: 5,
      brand: 'kate spade',
      rating: 4.7,
      numReviews: 10,
      description: 'shoes',
    },
    {
      // _id: '4',
      name: 'kate spade lether shoes',
      slug: 'kate-spade-lether-shoes',
      category: 'shoes',
      images: '/images/p4.jpg',
      price: 110,
      countInStock: 5,
      brand: 'kate spade',
      rating: 4.6,
      numReviews: 10,
      description: 'lether shoes',
    },
  ],
};
export default data;
